### ISSUE TITLE
Author not visible in Books - table

### ISSUE THREAD

**Issue by HoldYourBreath** [HoldYourBreath/Library#16]
Array for authors is empty while other elements are provided, therefore Books - table is not populated with Author

0
:
authors
:
[]
description
:
"-- Ward Cunningham Straight from the programming trenches, The Pragmatic Programmer cuts through the increasing specialization and technicalities of modern software development to examine the core process--taking a requirement and producing working, maintainable code that delights its users. It covers topics ranging from personal responsibility and career development to architectural techniques for keeping your code flexible and easy to adapt and reuse. Read this book, and youll learn how to *Fight software rot; *Avoid the trap of duplicating knowledge; *Write flexible, dynamic, and adaptable code; *Avoid programming by coincidence; *Bullet-proof your code with contracts, assertions, and exceptions; *Capture real requirements; *Test ruthlessly and effectively; *Delight your users; *Build teams of pragmatic programmers; and *Make your developments more precise with automation. Written as a series of self-contained sections and filled with entertaining anecdotes, thoughtful examples, and interesting analogies, The Pragmatic Programmer illustrates the best practices and major pitfalls of many different aspects of software development. Whether youre a new coder, an experienced programm"
format
:
"Paperback"
isbn
:
9780201616224
loaned
:
false
pages
:
321
publication_date
:
"1999 10 30"
publisher
:
"Addison-Wesley Professional"
room_id
:
3
tag
:
8785434343
thumbnail
:
"https://images.gr-assets.com/books/1401432508s/4099.jpg"
title
:
"The Pragmatic Programmer: From Journeyman to Master"

**Comment by civing** [comment]
solved by c163031
