### ISSUE TITLE
Redirect correctly on login/logout

### ISSUE THREAD

**Issue by civing** [HoldYourBreath/Library#5]
Logins should redirect the user to previous visited page
Logouts should redirect the user to the front page

**Comment by civing** [comment]
@HoldYourBreath Did you not fix this?

**Comment by HoldYourBreath** [comment]
I have this patch on the issue. https://github.com/HoldYourBreath/Library/commit/0b70dc0b3f1c2dc76902ed2a91992a5fb981a71f
We talked that logouts were the important thing as the login was more problematic to implement, it will also now go to the home page.
